# Generated by Django 5.1 on 2025-04-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_created_at_article_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
