# Generated by Django 5.1 on 2025-04-22 11:32

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_article_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
