# Generated by Django 5.1 on 2025-07-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_articleimage_user_alter_articleimage_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='html_content',
        ),
        migrations.AddField(
            model_name='article',
            name='markdown_content',
            field=models.TextField(default='markdown content'),
            preserve_default=False,
        ),
    ]
