# Generated by Django 5.1 on 2025-04-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
